name: CI

env:
  CI: true

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  integration-price-oracle:
    name: Integration price oracle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}} ${{secrets.OPTIMISM_RPC}} ${{secrets.ARBITRUM_RPC}} ${{secrets.GNOSIS_RPC}}
      - name: Build
        run: yarn build
      - name: Test price oracle mainnet
        run: yarn workspace @mimic-fi/v2-price-oracle test:mainnet
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  integration-swap-connector:
    needs: integration-price-oracle
    name: Integration swap connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}} ${{secrets.OPTIMISM_RPC}} ${{secrets.ARBITRUM_RPC}} ${{secrets.GNOSIS_RPC}}
      - name: Build
        run: yarn build
      - name: Test swap connector mainnet
        run: yarn workspace @mimic-fi/v2-swap-connector test:mainnet
      - name: Test swap connector polygon
        run: yarn workspace @mimic-fi/v2-swap-connector test:polygon
      - name: Test swap connector optimism
        run: yarn workspace @mimic-fi/v2-swap-connector test:optimism
      - name: Test swap connector arbitrum
        run: yarn workspace @mimic-fi/v2-swap-connector test:arbitrum
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  integration-bridge-connector:
    needs: integration-swap-connector
    name: Integration bridge connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}} ${{secrets.OPTIMISM_RPC}} ${{secrets.ARBITRUM_RPC}} ${{secrets.GNOSIS_RPC}}
      - name: Build
        run: yarn build
      - name: Test bridge connector mainnet
        run: yarn workspace @mimic-fi/v2-bridge-connector test:mainnet
      - name: Test bridge connector polygon
        run: yarn workspace @mimic-fi/v2-bridge-connector test:polygon
      - name: Test bridge connector optimism
        run: yarn workspace @mimic-fi/v2-bridge-connector test:optimism
      - name: Test bridge connector arbitrum
        run: yarn workspace @mimic-fi/v2-bridge-connector test:arbitrum
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  integration-smart-vault:
    needs: integration-bridge-connector
    name: Integration smart vault
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}} ${{secrets.OPTIMISM_RPC}} ${{secrets.ARBITRUM_RPC}} ${{secrets.GNOSIS_RPC}}
      - name: Build
        run: yarn build
      - name: Test smart vault mainnet
        run: yarn workspace @mimic-fi/v2-smart-vault test:mainnet
      - name: Test smart vault polygon
        run: yarn workspace @mimic-fi/v2-smart-vault test:polygon
      - name: Test smart vault optimism
        run: yarn workspace @mimic-fi/v2-smart-vault test:optimism
      - name: Test smart vault arbitrum
        run: yarn workspace @mimic-fi/v2-smart-vault test:arbitrum
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
