name: CI

env:
  CI: true

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  integration-price-oracle:
    name: Integration price oracle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}} ${{secrets.OPTIMISM_RPC}} ${{secrets.ARBITRUM_RPC}} ${{secrets.GNOSIS_RPC}} ${{secrets.BSC_RPC}} ${{secrets.FANTOM_RPC}} ${{secrets.AVALANCHE_RPC}}
      - name: Build
        run: yarn build
      - name: Test price oracle mainnet
        run: yarn workspace @mimic-fi/v2-price-oracle test:mainnet
      - name: Test price oracle polygon
        run: yarn workspace @mimic-fi/v2-price-oracle test:polygon
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  integration-swap-connector:
    needs: integration-price-oracle
    name: Integration swap connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}} ${{secrets.OPTIMISM_RPC}} ${{secrets.ARBITRUM_RPC}} ${{secrets.GNOSIS_RPC}} ${{secrets.BSC_RPC}} ${{secrets.FANTOM_RPC}} ${{secrets.AVALANCHE_RPC}}
      - name: Build
        run: yarn build
      - name: Test swap connector mainnet
        run: yarn workspace @mimic-fi/v2-swap-connector test:mainnet
      - name: Test swap connector polygon
        run: yarn workspace @mimic-fi/v2-swap-connector test:polygon
      - name: Test swap connector optimism
        run: yarn workspace @mimic-fi/v2-swap-connector test:optimism
      - name: Test swap connector arbitrum
        run: yarn workspace @mimic-fi/v2-swap-connector test:arbitrum
      - name: Test swap connector gnosis
        run: yarn workspace @mimic-fi/v2-swap-connector test:gnosis
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  integration-bridge-connector:
    needs: integration-swap-connector
    name: Integration bridge connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}} ${{secrets.OPTIMISM_RPC}} ${{secrets.ARBITRUM_RPC}} ${{secrets.GNOSIS_RPC}} ${{secrets.BSC_RPC}} ${{secrets.FANTOM_RPC}} ${{secrets.AVALANCHE_RPC}}
      - name: Build
        run: yarn build
      - name: Test bridge connector mainnet
        run: yarn workspace @mimic-fi/v2-bridge-connector test:mainnet
      - name: Test bridge connector polygon
        run: yarn workspace @mimic-fi/v2-bridge-connector test:polygon
      - name: Test bridge connector optimism
        run: yarn workspace @mimic-fi/v2-bridge-connector test:optimism
      - name: Test bridge connector arbitrum
        run: yarn workspace @mimic-fi/v2-bridge-connector test:arbitrum
      - name: Test bridge connector gnosis
        run: yarn workspace @mimic-fi/v2-bridge-connector test:gnosis
      - name: Test bridge connector bsc
        run: yarn workspace @mimic-fi/v2-bridge-connector test:bsc
      - name: Test bridge connector fantom
        run: yarn workspace @mimic-fi/v2-bridge-connector test:fantom
      - name: Test bridge connector avalanche
        run: yarn workspace @mimic-fi/v2-bridge-connector test:avalanche
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  integration-smart-vault:
    needs: integration-bridge-connector
    name: Integration smart vault
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}} ${{secrets.OPTIMISM_RPC}} ${{secrets.ARBITRUM_RPC}} ${{secrets.GNOSIS_RPC}} ${{secrets.BSC_RPC}} ${{secrets.FANTOM_RPC}} ${{secrets.AVALANCHE_RPC}}
      - name: Build
        run: yarn build
      - name: Test smart vault mainnet
        run: yarn workspace @mimic-fi/v2-smart-vault test:mainnet
      - name: Test smart vault polygon
        run: yarn workspace @mimic-fi/v2-smart-vault test:polygon
      - name: Test smart vault optimism
        run: yarn workspace @mimic-fi/v2-smart-vault test:optimism
      - name: Test smart vault arbitrum
        run: yarn workspace @mimic-fi/v2-smart-vault test:arbitrum
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  integration-strategies:
    needs: integration-smart-vault
    name: Integration strategies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}} ${{secrets.OPTIMISM_RPC}} ${{secrets.ARBITRUM_RPC}} ${{secrets.GNOSIS_RPC}} ${{secrets.BSC_RPC}} ${{secrets.FANTOM_RPC}} ${{secrets.AVALANCHE_RPC}}
      - name: Build
        run: yarn build
      - name: Test strategies mainnet
        run: yarn workspace @mimic-fi/v2-strategies test:mainnet
      - name: Test strategies arbitrum
        run: yarn workspace @mimic-fi/v2-strategies test:arbitrum
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
